#!/bin/sh
#rm ./data/drop_rate
#rm ./data/delay_rate
#rm ./data/throughput_rate

#for a in $(seq 30)   #flow的个数
for a in 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 30;
do
	for b in $(seq 100)     #测试的次数
	do
		ns wireless-aodv-tdma.tcl $a > ./data02/data02.tcl

		#echo -n "$a	" >> ./data02/drop_rate7o
		#gawk -f drop.awk aodv-tdma.tr >> ./data02/drop_rate7o

		#echo -n "$a	" >> ./data02/delay_rate5o
		#gawk -f delay.awk aodv-tdma.tr >> ./data02/delay_rate5o

		echo -n "$a	" >> ./data02/throughput_rate5
		gawk -f throughput.awk aodv-tdma.tr >> ./data02/throughput_rate5
	done
done
exit 0
